name: Auto commit

on:
  push:
    branches:
      - main
      
  schedule:
  - cron: "0 0 * * *" # See https://crontab.guru/every-day-at-midnight

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0
         
      - name: Pull latest changes
        run: git pull --rebase origin main || echo "No changes to pull"

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "jordan.chancellor.15@gmail.com"
          git config --local user.name "jordanchancellor"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "🪩 auto commit"
          else
            echo "No changes to commit"
          fi
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
